# Generated by Django 5.0.6 on 2025-02-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mymodel_remove_reservation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
