# Generated by Django 5.0.6 on 2025-02-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_reservation_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.CharField(max_length=10),
        ),
    ]
